config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get 'booking/index'
  get 'admin/login'
  post 'admin/login'
  get 'admin/logout'
  get 'admin/home'
  get 'admin/fix_history'
  get 'fix/index'
  get 'fix/new'
  get 'fix/index'
  post 'fix/create'
  get 'fix/new'
  devise_for :users
  get 'home/index'
  post 'home/index'
  get 'home/about'
  get 'home/contact'
  get 'home/select'
  get 'home/full_view'
  get 'home/checkout'
  post 'home/checkout'
  get "purchase_completed", to: "home#purchase_completed"
  post "checkout", to:"home#checkout"
  get 'home/search'
  post 'home/search'
  resources :rooms
  resources :hotels
  resources :cities
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/admin/_navadmin.html.erb
<body data-spy="scroll" data-target=".navbar" data-offset="40" id="home">
               <% if notice %>
<p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
<p class="alert alert-danger"><%= alert %></p>
<% end %>
    
    <!-- Page Navigation -->
  
   

    <nav class="navbar navbar-expand-lg navbar-dark bg-info">
    <style>
  .logo {
    padding-right: 10px;
    border-radius: 50%
  }
</style>

<img src="/assets/logo.png" alt="Bootstrap" width="60" height="45" class="logo">
    
    
   <a class="navbar-brand" style="padding: 10px;" href="/home/index">Book my room</a>
   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
     <span class="navbar-toggler-icon"></span>
   </button>
 
   <div class="collapse navbar-collapse" id="navbarColor01">
     <ul class="navbar-nav mr-auto">
       <li class="nav-item active" style="padding: 10px;">
         <a class="nav-link font-weight-bold" href="/admin/home">Home <span class="sr-only">(current)</span></a>
       </li>
       
      
      
      
     </ul>
     <style>
  .my-form {
    padding-right: 20px;
  }
</style>



  
   </div>
  
 <div>
 <meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  font-family: "Lato", sans-serif;
}

.sidenav {
  height: 100%;
  width: 0;
  position: fixed;
  z-index: 1;
  top: 0;
  right: 0;
  background-color: #111;
  overflow-x: hidden;
  transition: 0.5s;
  padding-top: 60px;
}

.sidenav a {
  padding: 8px 8px 8px 32px;
  text-decoration: none;
  font-size: 25px;
  color: #818181;
  display: block;
  transition: 0.3s;
}

.sidenav a:hover {
  color: #f1f1f1;
}

.sidenav .closebtn {
  position: absolute;
  top: 0;
  right: 25px;
  font-size: 36px;
  margin-left: 50px;
}

@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
}
</style>
</head>
<body>
<div class="container">
<div id="mySidenav" class="sidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <a href="/home/about">About</a>
  <li class="nav-item">
  <% if session[:admin].nil? %>
  <li><a href="/admin/login">Admin Login </a></li>
   <% else %>
  <li><a href ="/admin/logout"> Admin Logout </a></li>
   <% end %>
  
</div>




<span style="font-size:30px;cursor:pointer" onclick="openNav()"><svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
<path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
<path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
</svg></span>

<script>
function openNav() {
  document.getElementById("mySidenav").style.width = "250px";
}

function closeNav() {
  document.getElementById("mySidenav").style.width = "0";
}
</script>
   </div>
   </div>

 </nav>   
 </body>

app/views/admin/fix_history.html.erb
<%= render 'navadmin' %>
<div class="fix-table">
<table class="table table-striped table-hover">
                         
<thead class="thead-light">
  <tr>
  
    <th scope="col">Guest </th>
    <th scope="col">Email</th>
    <th scope="col">Room_No</th>
    <th scope="col">Price</th>
    <th scope="col">Hotel</th>
    <th scope="col">City</th>
    <th scope="col">check_in_date </th>
    <th scope="col">check_out_date</th>
  </tr>
</thead>
 
<tbody>
<% @fix_history.each do |f| %> 
<tr>
  
    <td><%= f.user.name %></td> 
    <td><%= f.user.email %></td>
    <td><%= f.room.no %></td>
    <td><%= f.total_price %></td>
    <td><%= f.room.hotel.name %></td>
    <td><%= f.room.hotel.city.name %></td>
    <td><%= f.fix.check_in %></td>
    <td><%= f.fix.check_out %></td> 
</tr>
<% end %>                   
</tbody>     

   
  
  
</table>
</div>
<div class="fix-his">
<%= link_to "admin Home" ,admin_home_path,:class=> "btn btn-warning text-dark" %>
</div>

app/views/admin/home.html.erb
<%= render 'navadmin' %>


<center><h5 class="card-title">
<?xml version="1.0" ?><svg height="25" viewBox="0 0 48 48" width="25" xmlns="http://www.w3.org/2000/svg"><path d="M0 0h48v48h-48z" fill="none"/><path d="M6 26h16v-20h-16v20zm0 16h16v-12h-16v12zm20 0h16v-20h-16v20zm0-36v12h16v-12h-16z"/></svg>DASHBOARD</h5></center>
<hr>

<div class="container">
<div class="row mx-5">
<div class="col-sm-3 mt-5">
<div class="card text-white bg-success bg-gradient mb-3" style="max-width: 18rem;">
<div class="card-header"> <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-book" viewBox="0 0 16 16">
<path d="M1 2.828c.885-.37 2.154-.769 3.388-.893 1.33-.134 2.458.063 3.112.752v9.746c-.935-.53-2.12-.603-3.213-.493-1.18.12-2.37.461-3.287.811V2.828zm7.5-.141c.654-.689 1.782-.886 3.112-.752 1.234.124 2.503.523 3.388.893v9.923c-.918-.35-2.107-.692-3.287-.81-1.094-.111-2.278-.039-3.213.492V2.687zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783z"/>
</svg> <%= link_to "UsersBooking",admin_fix_history_path ,class:" text-white"  %></div>
<div class="card-body" style="padding: 27px 7px;">

  <h5 class="card-title">UsersBooking</h5>
  <h6>Number of Bookings: <%= Order.count %></h6>
</div>
</div>

</div>

<div class="col-sm-3 mt-5">

<div class="card text-white bg-danger  bg-gradient mb-3" style="max-width: 18rem;">
  <div class="card-header"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-alt-fill" viewBox="0 0 16 16">
  <path d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10zm0-7a3 3 0 1 1 0-6 3 3 0 0 1 0 6z"/>
</svg>
<%=link_to "Cities",cities_url,class:" text-white" %></div>
  <div class="card-body" style="padding: 27px 7px;">
    <h5 class="card-title">City</h5>
    <h6>Number of cities: <%= City.count %></h6>
      

  </div>
</div>
</div>
<div class="col-sm-3 mt-5">
<div class="card text-white bg-warning bg-gradient mb-3" style="max-width: 18rem;">
  <div class="card-header"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-building" viewBox="0 0 16 16">
  <path d="M4 2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1Zm3 0a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1Zm3.5-.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1ZM4 5.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1ZM7.5 5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1Zm2.5.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1ZM4.5 8a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1Zm2.5.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1Zm3.5-.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1Z"/>
  <path d="M2 1a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1v14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V1Zm11 0H3v14h3v-2.5a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 .5.5V15h3V1Z"/>
</svg>

<%= link_to "Hotels",hotels_url,class:" text-white" %></div>
  <div class="card-body" style="padding: 27px 7px;">
    <h5 class="card-title">Hotels</h5>
    <h6>Number of hotels: <%= Hotel.count %></h6>
    

  </div>
</div>
</div>
<div class="col-sm-3 mt-5">
<div class="card text-white bg-info  bg-gradient mb-3" style="max-width: 18rem;">
  <div class="card-header"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house-fill" viewBox="0 0 16 16">
  <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L8 2.207l6.646 6.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.707 1.5Z"/>
  <path d="m8 3.293 6 6V13.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5V9.293l6-6Z"/>
</svg>
<%= link_to "Rooms" ,rooms_url,class:" text-white" %></div>
  <div class="card-body" style="padding: 27px 7px;">
  
    <h5 class="card-title">Rooms</h5>
    <h6>Number of rooms: <%= Room.count %></h6>
     

  </div>
</div>
</div>
</div>








</div>
 



  

app/views/admin/login.html.erb
<section class="h-100 gradient-form" style="background-color: #eee;">
<div class="container py-5 h-100">
  <div class="row d-flex justify-content-center align-items-center h-100">
    <div class="col-xl-10">
      <div class="card rounded-3 text-black">
        <div class="row g-0">
          <div class="col-lg-6">
            <div class="card-body p-md-5 mx-md-4">

              <div class="text-center">
                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/lotus.webp"
                  style="width: 185px;" alt="logo">
                <h4 class="mt-1 mb-5 pb-1">Admin login</h4>
              </div>
             
              
                <%=form_with url:"/admin/login",method: :post do |form| %>
                    
                    <p>Please login to your account</p>

                    <div class="form-outline mb-4">
                        <div class="field" >
                            <%= form.label :username %>
                            <%= form.text_field :username %>
                        </div>

                    <div class="form-outline mb-4">
                        <div class ="field">
                            <%= form.label :password %>
                            <%= form.password_field :password %>
                        </div>
                    </div>

                    <div class="d-flex align-items-center justify-content-center pb-4">
                        <div class="actions">
                        <%= form.submit "Admin Login" %>
                    </div>
                    </div>
                <% end %>
                

            </div>
          </div>
          
        </div>
      </div>
    </div>
  </div>
</div>
</section>








    

  