config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get 'booking/index'
  get 'admin/login'
  post 'admin/login'
  get 'admin/logout'
  get 'admin/home'
  get 'admin/fix_history'
  get 'fix/index'
  get 'fix/new'
  get 'fix/index'
  post 'fix/create'
  get 'fix/new'
  devise_for :users
  get 'home/index'
  post 'home/index'
  get 'home/about'
  get 'home/contact'
  get 'home/select'
  get 'home/full_view'
  get 'home/checkout'
  post 'home/checkout'
  get "purchase_completed", to: "home#purchase_completed"
  post "checkout", to:"home#checkout"
  get 'home/search'
  post 'home/search'
  resources :rooms
  resources :hotels
  resources :cities
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @cities = City.all
  end

  def select
    @room= Hotel.find(params[:hotel_id])
  end

  def full_view
    puts "view method called with params: #{params}"
    Rails.logger.info "yoo"
    @hotels= City.find(params[:city_id])
  end

  def checkout
   
    @fix= Fix.find(params[:id])
    @days= (@fix.check_out.to_date  - @fix.check_in.to_date ).to_i
    amount_to_charge = session[:amount].to_i * @days
    p amount_to_charge
    @id=params[:id]
	if request.post?
    p"---------------------Start-------------------"
	
		ActiveMerchant::Billing::Base.mode = :test
		
		credit_card = ActiveMerchant::Billing::CreditCard.new(
		:first_name         => params[:first_name],
		:last_name          => params[:last_name],
		:number             => params[:credit_card_no].to_i,
		:month              => params[:check][:month].to_i,
		:year               => params[:check][:year].to_i,
		:verification_value => params[:verification_number].to_i)
   
		gateway =ActiveMerchant::Billing::TrustCommerceGateway.new(
		:login => 'TestMerchant',
		:password =>'password',
		:test => 'true' )
   
		response = gateway.authorize(amount_to_charge , credit_card)

		puts response.inspect
		if response.success?
   
			gateway.capture(amount_to_charge, response.authorization)
     
			fix=Fix.find(params[:id])
        p fix
        order=Hash.new
        
        order[:fix_id]=fix.id
        order[:user_id]=fix.user_id
        order[:room_id]=fix.room_id
        order[:total_price]=amount_to_charge
       
        p "------------1st----------"
        p order
        orderdetails=Order.new(order)
        orderdetails.save

        purchase_completed=orderdetails.id
        p "------------1st--------------------------------------------------"
        p purchase_completed
      
        
			redirect_to purchase_completed_path(:id => purchase_completed)
		else
			flash[:notice]= "Something went wrong.Try again"
			render :action => "checkout"
		end	
	end
  end
  def search
    keyword = '%' + params[:keyword] + '%'
    @search = City.find_by_sql ["Select * from cities WHERE name like ? ",keyword]
  end
 def purchase_completed
  @fix=Order.find(params[:id])  
 end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_nav.html.erb
<body data-spy="scroll" data-target=".navbar" data-offset="40" id="home">
               <% if notice %>
<p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
<p class="alert alert-danger"><%= alert %></p>
<% end %>
    
    <!-- Page Navigation -->
  
   

    <nav class="navbar navbar-expand-lg navbar-dark bg-info">
    <style>
  .logo {
    padding-right: 10px;
    border-radius: 50%
  }
</style>

<img src="/assets/logo.png" alt="Bootstrap" width="60" height="45" class="logo">
    
    
   <a class="navbar-brand" style="padding: 10px;" href="/home/index">Book my room</a>
   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
     <span class="navbar-toggler-icon"></span>
   </button>
 
   <div class="collapse navbar-collapse" id="navbarColor01">
     <ul class="navbar-nav mr-auto">
       <li class="nav-item active" style="padding: 10px;">
         <a class="nav-link  font-weight-bold" href="/home/index">Home <span class="sr-only">(current)</span></a>
       </li>
       

       <ul class="navbar-nav mr-auto">
       <li class="nav-item active" style="padding: 10px;">
         <a class="nav-link font-weight-bold " href="/home/about">About <span class="sr-only">(current)</span></a>
       </li>
       </ul>
      
      
     </ul>
     <style>
  .my-form {
    padding-right: 20px;
  }
</style>

<%= form_with url: "/home/search",class:"d-flex my-form",local: true, method: :post do |form| %>
  <%= form.text_field :keyword ,class:"form-control me-2" ,placeholder:"Search" %>
  <%= form.submit "Search" ,class:"btn btn-success"%>
<% end %>

  
   </div>
  
 <div>
 <meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  font-family: "Lato", sans-serif;
}

.sidenav {
  height: 100%;
  width: 0;
  position: fixed;
  z-index: 1;
  top: 0;
  right: 0;
  background-color: #111;
  overflow-x: hidden;
  transition: 0.5s;
  padding-top: 60px;
}

.sidenav a {
  padding: 8px 8px 8px 32px;
  text-decoration: none;
  font-size: 25px;
  color: #818181;
  display: block;
  transition: 0.3s;
}

.sidenav a:hover {
  color: #f1f1f1;
}

.sidenav .closebtn {
  position: absolute;
  top: 0;
  right: 25px;
  font-size: 36px;
  margin-left: 50px;
}

@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
}
</style>
</head>
<body>
<div class="container">
<div id="mySidenav" class="sidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <a href="/home/about">About </a>
  <li class="nav-item">
          <% if user_signed_in? %>
          <h6 class ="text-primary"> logged <strong><%= current_user.email %></strong></h6>.
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
          </li>
  <a href="/booking/index">My Bookings</a>
  <a href="/home/contact">Contact</a>
</div>




<span style="font-size:30px;cursor:pointer" onclick="openNav()"><svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
<path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
<path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
</svg></span>

<script>
function openNav() {
  document.getElementById("mySidenav").style.width = "250px";
}

function closeNav() {
  document.getElementById("mySidenav").style.width = "0";
}
</script>
   </div>
   </div>

 </nav>   
 </body>

app/views/home/about.html.erb
<%= render 'nav' %>

<div class="container">

<div class="container-fluid">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3>Welcome to our
                Book my room</h3>
            </div>
            <div class="modal-body">
                <div class="col-3"></div>
                <div class="quiz" id="quiz" data-toggle="buttons">
                    <label class="element-animation1 btn btn-lg btn-info btn-block"><span class="btn-label"><i class="glyphicon glyphicon-chevron-right"></i></span>
                    We know that planning a trip can be overwhelming, which is why we created a simple and convenient platform for booking the perfect hotel. With just a few clicks, you can easily compare prices, amenities, and locations of various hotels and make a reservation.
                    
                    Our team is dedicated to providing the best possible experience for our users. We are constantly updating our selection of hotels and working to secure the best rates and deals. We also prioritize the safety and security of our users, which is why we use secure payment methods and have a dedicated customer support team available to assist with any issues or questions.
                    
                    Thank you for choosing our hotel booking application. We look forward to helping you plan your next trip!
                    
                    
                  </label>
                    
                </div>
            </div>
            <div class="container text-center">
            <div class="row">
              <div class="col">
              <img src="/assets/aboutus.jpeg" alt="About us" width="500" height="600">
              </div>
              <div class="col">
              <img src="/assets/about.webp" alt="About us" width="500" height="600">
              </div>
            </div>
            </div>
            
            
        </div>
    </div>
</div>

app/views/home/checkout.html.erb
<%= render 'nav' %>




<%=flash[:notice] %>






  
	
<br>


  <section class="intro">
  <div class="bg-image-vertical h-100" style="background-color: #EFD3E4;
          background-image: url(https://mdbootstrap.com/img/Photos/new-templates/search-box/img1.jpg);
        ">
    <div class="mask d-flex align-items-center h-100">
      <div class="container" style ="padding-bottom:200px;">
        <div class="row justify-content-center">
          <div class="col-12 col-lg-10">
            <div class="card">
            <div class="card-body p-5">
			<div class="checkout">
                <h1 class="mb-5 text-center">Checkout Form</h1>

				<h3> Total amount to be paid : <%= (session[:amount]* @days) %> </h3>

				<%= form_with url: checkout_path(:id=>@id), method: :post do |f| %>

                  <!-- 2 column grid layout with text inputs for the first and last names -->
                  <div class="row">
                    <div class="col-12 col-md-6 mb-4">
						<div class ="field">
							<%= f.label :first_name %><br>
							<%= f.text_field :first_name %>
						</div>
                    </div>
                    <div class="col-12 col-md-6 mb-4">
						<div class ="field">
							<%=f.label :last_name %> <br>
							<%=f.text_field :last_name %>
						</div>
                    </div>
                  </div>

                
                  
                  <div class="form-outline mb-4">
					<div class ="field">
						<%=f.label :credit_card_no %> <br>
						<%=f.text_field :credit_card_no %>
					</div>
                  </div>

                  <div class="row">
                    <div class="col-12 col-md-6 mb-4">
					<div class="field">
					<%= f.label :date_of_expiry %><br />
						<select name="check[month]" id="check_out_month">
						<option selected value="01">Janurary 
						<option  value="02">Feburary
						<option  value="03">March
						<option  value="04">April 
						<option  value="05">May 
						<option  value="06">June 
						<option  value="07">July 
						<option  value="08">August 
						<option  value="09">September 
						<option  value="10">October 
						<option  value="11">November 
						<option  value="12">December 
						</select>
						<select name="check[year]" id=check_out_year">
						<option selected value="2022">2022
						<option  value="2023">2023
						<option  value="2024">2024
						<option  value="2025">2025
						<option  value="2026">2026
						<option  value="2027">2027
						<option  value="2028">2028
						<option  value="2029">2029
						<option  value="2030">2030
						<option  value="2031">2031
						<option  value="2032">2032
						<option  value="2033">2033
					</select>
				  </div>
                    </div>
                    <div class="col-12 col-md-6 mb-4">
						<div class ="field">
						<%= f.label :verification_number %><br />
						<%= f.text_field :verification_number %>
						</div>
                    </div>
                  </div>
                  

                  <!-- Submit button -->
				  <div class="actions">
				  <%= f.submit "Submit"%>
				</div>
			<% end %>
                  

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>
</section>
  

app/views/home/contact.html.erb
<%= render 'nav' %>
<br>
<!--Section: Contact v.2-->
<section class="mb-4">

    <!--Section heading-->
    <h2 class="h1-responsive font-weight-bold text-center my-4">Contact us</h2>
    <!--Section description-->
    <h5 class="text-center w-responsive mx-auto mb-5">Do you have any questions? Please do not hesitate to contact us directly. Our team will come back to you within
        a matter of hours to help you.</h5>
<div class="container">
    <div class="row">

        <!--Grid column-->
        <div class="col-md-9 mb-md-0 mb-5">
            <form id="contact-form" name="contact-form" action="mail.php" method="POST">

                <!--Grid row-->
                <div class="row">

                    <!--Grid column-->
                    <div class="col-md-6">
                        <div class="md-form mb-0">
                            <input type="text" id="name" name="name" class="form-control">
                            <label for="name" class="">Your name</label>
                        </div>
                    </div>
                    <!--Grid column-->

                    <!--Grid column-->
                    <div class="col-md-6">
                        <div class="md-form mb-0">
                            <input type="text" id="email" name="email" class="form-control">
                            <label for="email" class="">Your email</label>
                        </div>
                    </div>
                    <!--Grid column-->

                </div>
                <!--Grid row-->

                <!--Grid row-->
                <div class="row">
                    <div class="col-md-12">
                        <div class="md-form mb-0">
                            <input type="text" id="subject" name="subject" class="form-control">
                            <label for="subject" class="">Subject</label>
                        </div>
                    </div>
                </div>
                <!--Grid row-->

                <!--Grid row-->
                <div class="row">

                    <!--Grid column-->
                    <div class="col-md-12">

                        <div class="md-form">
                            <textarea type="text" id="message" name="message" rows="2" class="form-control md-textarea"></textarea>
                            <label for="message">Your message</label>
                        </div>

                    </div>
                </div>
                <!--Grid row-->

            </form>

            <div class="text-center text-md-left">
                <a class="btn btn-primary" onclick="document.getElementById('contact-form').submit();">Send</a>
            </div>
            <div class="status"></div>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-3 text-center">
            <ul class="list-unstyled mb-0">
                <li><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-geo-alt-fill" viewBox="0 0 16 16">
                <path d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10zm0-7a3 3 0 1 1 0-6 3 3 0 0 1 0 6z"/>
              </svg>
                    <p>Bangalore,Karnataka, India</p>
                </li>
<hr>
                <li><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-telephone" viewBox="0 0 16 16">
                <path d="M3.654 1.328a.678.678 0 0 0-1.015-.063L1.605 2.3c-.483.484-.661 1.169-.45 1.77a17.568 17.568 0 0 0 4.168 6.608 17.569 17.569 0 0 0 6.608 4.168c.601.211 1.286.033 1.77-.45l1.034-1.034a.678.678 0 0 0-.063-1.015l-2.307-1.794a.678.678 0 0 0-.58-.122l-2.19.547a1.745 1.745 0 0 1-1.657-.459L5.482 8.062a1.745 1.745 0 0 1-.46-1.657l.548-2.19a.678.678 0 0 0-.122-.58L3.654 1.328zM1.884.511a1.745 1.745 0 0 1 2.612.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z"/>
              </svg>
                    <p>+ 01 234 567 89</p>
                </li>
<hr>
                <li><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-envelope" viewBox="0 0 16 16">
                <path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4Zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1H2Zm13 2.383-4.708 2.825L15 11.105V5.383Zm-.034 6.876-5.64-3.471L8 9.583l-1.326-.795-5.64 3.47A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.741ZM1 11.105l4.708-2.897L1 5.383v5.722Z"/>
              </svg>
                    <p>contact@bookmyroom.com</p>
                </li>
            </ul>
        </div>
        <!--Grid column-->

    </div>
    <%=link_to "BACK", home_index_path,{class:"btn btn-info text-dark"} %>
    </div>
</section>
<!--Section: Contact v.2-->

app/views/home/full_view.html.erb
<%= render 'nav' %>
<br>
<center><h2 class="text-dark font-weight-bold"><%=@hotels.name %></h2></center>
<hr>
<center><img src="/assets/ho.svg" alt="Girl in a jacket" width="100" height="100"> <h4> List Of Hotels </h4></center>
<br>
<table>
<tr>
<% count=0 %>

<% @hotels.hotels.each do |i| %>
<% if (count % 5)==0 %>
</tr>
<tr>
<% end %>
<% count+=1 %>
<td>

<div class="container">
<div class="city-style">
<div class="card" style="width: 20rem;">
<%= image_tag i.hotel_image ,height:"250",width:"320"%><br>
  <div class="card-body">
 
  <h6><span style="color: indigo;"><strong>
  <img src="/assets/hotel.svg" alt="Girl in a jacket" width="30" height="30"></strong></span><span><strong> <%=i.name %></strong></span></h6>
  <h6> <span style="color: green;"><strong><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-star-fill" viewBox="0 0 16 16">
  <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
</svg></strong></span><span> <%=i.hotel_type %></span></h6><br>
  <h6> <span style="color: green;"><strong><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-geo-alt-fill" viewBox="0 0 16 16">
  <path d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10zm0-7a3 3 0 1 1 0-6 3 3 0 0 1 0 6z"/>
</svg></strong></span> <span><%= i.address %></span></h6><br>
  
  <h6 style="color: purple;"><i><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-telephone" viewBox="0 0 16 16">
  <path d="M3.654 1.328a.678.678 0 0 0-1.015-.063L1.605 2.3c-.483.484-.661 1.169-.45 1.77a17.568 17.568 0 0 0 4.168 6.608 17.569 17.569 0 0 0 6.608 4.168c.601.211 1.286.033 1.77-.45l1.034-1.034a.678.678 0 0 0-.063-1.015l-2.307-1.794a.678.678 0 0 0-.58-.122l-2.19.547a1.745 1.745 0 0 1-1.657-.459L5.482 8.062a1.745 1.745 0 0 1-.46-1.657l.548-2.19a.678.678 0 0 0-.122-.58L3.654 1.328zM1.884.511a1.745 1.745 0 0 1 2.612.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z"/>
</svg></i> <%=i.contact%></h6>
  
  <%=link_to "Select" , home_select_path(:hotel_id=>i),{class:"btn btn-primary text-white"} %> |
  <%=link_to "BACK", home_index_path,{class:"btn btn-light text-dark"} %>
  
   
  </div>
</div>
</div>
</div>



</td>
<% end %>
</tr>
</table>

app/views/home/index.html.erb
<%= render 'nav' %>
<br>

<div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="/assets/pexels-chait-goli-2083838.jpg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="/assets/hotel.jpg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="/assets/pexels-pixabay-417192.jpg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="/assets/room.jpg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="/assets/india.jpg" class="d-block w-100" alt="...">
    </div>
  </div>
</div>
<br>
 <center><h2 class="text-dark font-weight-bold">CITIES  </h2></center>
<br>
<table>
<tr>
<% count=0 %>

<% @cities.each do |c| %>
<% if (count % 4)==0 %>
</tr>
<tr>
<% end %>
<% count+=1 %>
<td>
            <div class="container">
            <div class="city-style">
         
            <div class="card" style="width: 20rem;">
            <%= image_tag c.city_image ,height:"250",width:"320"%><br>
            <div class="card-body">
            <h3 class ="text-primary">
            <%=c.name %></h3>
            <hr>
            <div class="color-text">
            
            <%=link_to "View", home_full_view_path(:city_id=>c),{class:"btn btn-warning text-dark"} %>
            </div>
            </div>
          </div>
            </div>
            </div>

</td>
<% end %>
</tr>
</table>

app/views/home/purchase_completed.html.erb
<%= render 'nav' %>

<div class="container mt-5">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="alert alert-success text-center animate__animated animate__bounceIn">
        <h3>Thank you for your Booking!

        </h3>
        
      </div>
    </div>
  </div>
</div>
 <br>

 <center><h2> Booking Details </h2></center>





  

 


 
 


<br>


 
 <div class="col-lg-14 d-flex align-items-stretch  justify-content-center">
            
        
 <div class="card mb-3" style="max-width: 780px;">
  <div class="row g-0">
    <div class="col-md-7">
    <%= image_tag @fix.room.hotel.hotel_image ,height:"400",width:"420"%><br>
    </div>
    <div class="col-md-5">
      <div class="card-body">
      <h4 style="color: indigo;"><strong>  Guest Details</strong>
      <hr>
      <h5><em>  Name:<%= @fix.user.name %></em><br>
      <em> Email: <%= @fix.user.email  %></em><br>
      <em> Phone: <%= @fix.user.phone  %></em><br>
<hr>
    <h4 style="color: green;"><strong> Room Details</strong></h4>
    <hr>
      <i> Room Number: <%= @fix.room.no %></i><br>
        
      <i> Price: <%= @fix.total_price  %></i><br>
      
      <i> Hotel: <%= @fix.room.hotel.name  %></i><br>
      <i> Check-in: <%= @fix.fix.check_in %></i><br>
      <i>  Check-out: <%= @fix.fix.check_out%></i><br>
      <i> Address: <%= @fix.room.hotel.address %></i><br>
     </h5>
      </div>
    </div>
  </div>
</div>
</div>




<center><a href ="/home/index" class="btn btn-light text-dark"> Click to Continue  </a> 

<a href="/booking/index" class="btn btn-dark text-white">My Bookings</a></center>

app/views/home/search.html.erb
<%= render 'nav' %>

<table>
<tr>
<% count=0 %>

<% @search.each do |c| %>
<% if (count % 4)==0 %>
</tr>
<tr>
<% end %>
<% count+=1 %>
<td>
            <div class="city-style">
         
            <div class="card" style="width: 20rem;">
            <%= image_tag c.city_image ,height:"250",width:"320"%><br>
            <div class="card-body">
            <h3 class ="text-primary">
            <%=c.name %></h3>
            <hr>
            <%=link_to "View", home_full_view_path(:city_id=>c),{class:"btn btn-info text-white"} %>
    
            </div>
          </div>
            </div>


</td>
<% end %>
</tr>
</table>

app/views/home/select.html.erb
<%= render 'nav' %>
<br>
<center><h2 class="text-dark font-weight-bold"><%= @room.name %></h2>

</center>

<hr>
<center> <img src="/assets/ro.svg" alt="Girl in a jacket" width="100" height="100"><h4> List Of Rooms </h4></center>


<table>
<tr>
<% count=0 %>

<% @room.rooms.each do |i| %>
   

<% if (count%5)==0 %>
</tr>
<tr>
<% end %>
<% count +=1 %>
<td>
<div class="container">
<div class="city-style">
<div class="card" style="width: 20rem;">
<%= image_tag i.room_image ,height:"250",width:"320"%><br>
  <div class="card-body">
  <h6 class="text-secondary">
  <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-door-closed" viewBox="0 0 16 16">
  <path d="M3 2a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v13h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1H3V2zm1 13h8V2H4v13z"/>
  <path d="M9 9a1 1 0 1 0 2 0 1 1 0 0 0-2 0z"/>
</svg>: <%=i.no %><br>
<img src="/assets/ac.svg" alt="Girl in a jacket" width="40" height="40">
  <%=i.room_type %> <br>
  <img src="/assets/bed.svg" alt="Girl in a jacket" width="40" height="40">:<%= i.description %></h6>
  <img src="/assets/bathtub.svg" alt="Girl in a jacket" width="30" height="30">
  <img src="/assets/window.svg" alt="Girl in a jacket" width="30" height="30">
  <hr>
  <h6 class="text-danger"> <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-currency-rupee" viewBox="0 0 16 16">
  <path d="M4 3.06h2.726c1.22 0 2.12.575 2.325 1.724H4v1.051h5.051C8.855 7.001 8 7.558 6.788 7.558H4v1.317L8.437 14h2.11L6.095 8.884h.855c2.316-.018 3.465-1.476 3.688-3.049H12V4.784h-1.345c-.08-.778-.357-1.335-.793-1.732H12V2H4v1.06Z"/>
</svg><%= i.price %></h6> <br>
  <%=link_to "Book", fix_index_path(:room_id=>i.id),{class:"btn btn-info text-white"} %> 
  <%=link_to "BACK", home_index_path,{class:"btn btn-light text-dark"} %>
  
  </div>
</div>
</div>
</div>


</td>

<% end %>

</tr>
</table>