config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get 'booking/index'
  get 'admin/login'
  post 'admin/login'
  get 'admin/logout'
  get 'admin/home'
  get 'admin/fix_history'
  get 'fix/index'
  get 'fix/new'
  get 'fix/index'
  post 'fix/create'
  get 'fix/new'
  devise_for :users
  get 'home/index'
  post 'home/index'
  get 'home/about'
  get 'home/contact'
  get 'home/select'
  get 'home/full_view'
  get 'home/checkout'
  post 'home/checkout'
  get "purchase_completed", to: "home#purchase_completed"
  post "checkout", to:"home#checkout"
  get 'home/search'
  post 'home/search'
  resources :rooms
  resources :hotels
  resources :cities
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  has_one_attached :room_image
  belongs_to :hotel
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1 or /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to room_url(@room), notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to room_url(@room), notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:no, :room_type, :description, :price, :hotel_id,:room_image)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="hotel-card">

  <div class="field ,style="padding-top:100px;">
    <h5><strong><%= form.label :no ,{class: "form-label text-dark"}  %></strong></h5>
    <%= form.number_field :no,{class:"form-control"} %>
  </div>

  <div class="field">
  <h5>Room Type</h5>
  <%= form.label :room_type, "AC" %>
  <%= form.radio_button :room_type, "AC" %>
  <%= form.label :room_type, "Non-Ac" %>
  <%= form.radio_button :room_type, "Non-AC" %>
  
</div>

  <div class="field">
  <h5><strong><%= form.label :description,{class: "form-label"}  %></strong></h5>
    <%= form.text_area :description ,{class:"form-control"}%>
  </div>

  <div class="field">
  <h5><strong> <%= form.label :price,{class: "form-label"}  %></strong></h5>
    <%= form.text_field :price ,{class:"form-control"}%>
  </div>

  <div class="field">
  <h5><strong> <%= form.label :hotel_id ,{class: "form-label"} %></strong></h5>
    <%= form.text_field :hotel_id,{class:"form-control"} %>
  </div>

  <h5><strong><%= form.label :room_image %></strong></h5>
  <%= form.file_field :room_image %>

  <div class="actions">
    <%= form.submit %>
  </div>
  
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<%= render 'admin/navadmin' %>


<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

<div class="fix-table">
<table class="table table-striped table-hover">
  <thead class="table-dark">
    <tr>
      <th>No</th>
      <th>Room type</th>
      <th>Description</th>
      <th>Price</th>
      <th>Hotel</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.no %></td>
        <td><%= room.room_type %></td>
        <td><%= room.description %></td>
        <td><%= room.price %></td>
        <td><%= room.hotel_id %></td>
        <td><%= link_to 'Show', room , :class=> "btn btn-info text-dark"%></td>
        <td><%= link_to 'Edit', edit_room_path(room) , :class=> "btn btn-warning text-dark"%></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' }, :class=> "btn btn-danger text-white" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>
<center>
<%= link_to 'New Room', new_room_path, :class=> "btn btn-success text-white" %>|
<%= link_to "Adminhome", admin_home_path, :class=> "btn btn-light text-dark" %>
</center>

app/views/rooms/new.html.erb
<center><h1>New Room</h1></center>

<%= render 'form', room: @room %>

<center><%= link_to 'Back', rooms_path,:class=> "btn btn-outline-dark" %></center>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>
<%= image_tag @room.room_image %>
<p>
  <strong>No:</strong>
  <%= @room.no %>
</p>

<p>
  <strong>Room type:</strong>
  <%= @room.room_type %>
</p>

<p>
  <strong>Description:</strong>
  <%= @room.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @room.price %>
</p>

<p>
  <strong>Hotel:</strong>
  <%= @room.hotel_id %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>