config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get 'booking/index'
  get 'admin/login'
  post 'admin/login'
  get 'admin/logout'
  get 'admin/home'
  get 'admin/fix_history'
  get 'fix/index'
  get 'fix/new'
  get 'fix/index'
  post 'fix/create'
  get 'fix/new'
  devise_for :users
  get 'home/index'
  post 'home/index'
  get 'home/about'
  get 'home/contact'
  get 'home/select'
  get 'home/full_view'
  get 'home/checkout'
  post 'home/checkout'
  get "purchase_completed", to: "home#purchase_completed"
  post "checkout", to:"home#checkout"
  get 'home/search'
  post 'home/search'
  resources :rooms
  resources :hotels
  resources :cities
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  has_one_attached :hotel_image
  belongs_to :city
  has_many :rooms
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: %i[ show edit update destroy ]

  # GET /hotels or /hotels.json
  def index
    @hotels = Hotel.all
  end

  # GET /hotels/1 or /hotels/1.json
  def show
  end

  # GET /hotels/new
  def new
    @hotel = Hotel.new
  end

  # GET /hotels/1/edit
  def edit
  end

  # POST /hotels or /hotels.json
  def create
    @hotel = Hotel.new(hotel_params)

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to hotel_url(@hotel), notice: "Hotel was successfully created." }
        format.json { render :show, status: :created, location: @hotel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotels/1 or /hotels/1.json
  def update
    respond_to do |format|
      if @hotel.update(hotel_params)
        format.html { redirect_to hotel_url(@hotel), notice: "Hotel was successfully updated." }
        format.json { render :show, status: :ok, location: @hotel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1 or /hotels/1.json
  def destroy
    @hotel.destroy

    respond_to do |format|
      format.html { redirect_to hotels_url, notice: "Hotel was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hotel_params
      params.require(:hotel).permit(:name, :hotel_type, :address, :owner, :contact, :city_id,:hotel_image)
    end
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/hotels/_form.html.erb
<%= form_with(model: hotel, local: true) do |form| %>
  <% if hotel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hotel.errors.count, "error") %> prohibited this hotel from being saved:</h2>

      <ul>
        <% hotel.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <div class= "hotel-card">
 
    

      <div class="field">
      <h5><strong><%= form.label :name,{class: "form-label"} %></strong></h5>
        <%= form.text_field :name,{class:"form-control"} %>
      </div>

      <div class="field">
      <h5><strong><%= form.label :hotel_type,{class: "form-label"} %></strong></h5>
        <%= form.text_field :hotel_type,{class:"form-control"} %>
      </div>

      <div class="field">
      <h5><strong> <%= form.label :address,{class: "form-label"} %></strong></h5>
        <%= form.text_area :address,{class:"form-control"} %>
      </div>

      <div class="field">
      <h5><strong><%= form.label :owner,{class: "form-label"} %></strong></h5>
        <%= form.text_field :owner,{class:"form-control"} %>
      </div>

      <div class="field">
      <h5><strong><%= form.label :contact,{class: "form-label"} %></strong></h5>
        <%= form.number_field :contact,{class:"form-control"} %>
      </div>

      <div class="field">
      <h5><strong><%= form.label :city_id ,{class: "form-label"}%></strong></h5>
        <%= form.text_field :city_id,{class:"form-control"} %>
      </div>


      <h5><strong><%= form.label :hotel_image %></strong></h5>
      <%= form.file_field :hotel_image %>

      <div class="actions">
        <%= form.submit %>
      </div>

 
  </div>
<% end %>



 

    

app/views/hotels/edit.html.erb
<h1>Editing Hotel</h1>

<%= render 'form', hotel: @hotel %>

<%= link_to 'Show', @hotel %> |
<%= link_to 'Back', hotels_path %>

app/views/hotels/index.html.erb
<%= render 'admin/navadmin' %>

<p id="notice"><%= notice %></p>

<h1>Hotels</h1>

<div class="fix-table">
<table class="table table-striped table-hover">
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Hotel type</th>
      <th>Address</th>
      <th>Owner</th>
      <th>Contact</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  
  <tbody>
  
    <% @hotels.each do |hotel| %>
      <tr>
        <td><%= hotel.name %></td>
        <td><%= hotel.hotel_type %></td>
        <td><%= hotel.address %></td>
        <td><%= hotel.owner %></td>
        <td><%= hotel.contact %></td>
        <td><%= hotel.city_id %></td>
        <td><%= link_to 'Show', hotel, :class=> "btn btn-info text-dark" %></td>
        <td><%= link_to 'Edit', edit_hotel_path(hotel), :class=> "btn btn-warning text-dark" %></td>
        <td><%= link_to 'Destroy', hotel, method: :delete, data: { confirm: 'Are you sure?' }, :class=> "btn btn-danger text-white" %></td>
      </tr>
    <% end %>
  </tbody>
  </table>

</div>
<br>
<center>
<%= link_to 'New Hotel', new_hotel_path ,:class=> "btn btn-success text-white" %>|
<%= link_to "Adminhome", admin_home_path, :class=> "btn btn-light text-dark" %>
</center>

app/views/hotels/new.html.erb
<center><h1>New Hotel</h1></center>

<%= render 'form', hotel: @hotel %>

<center><%= link_to 'Back', hotels_path,:class=> "btn btn-outline-dark" %></center>

app/views/hotels/show.html.erb
<p id="notice"><%= notice %></p>
<%= image_tag  @hotel.hotel_image %>
<p>
  <strong>Name:</strong>
  <%= @hotel.name %>
</p>

<p>
  <strong>Hotel type:</strong>
  <%= @hotel.hotel_type %>
</p>

<p>
  <strong>Address:</strong>
  <%= @hotel.address %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @hotel.owner %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @hotel.contact %>
</p>

<p>
  <strong>City:</strong>
  <%= @hotel.city_id %>
</p>

<% @hotel.rooms.each do |i| %>
  Room_NO: <%=i.no %><br>
  
 <% end %>

<%= link_to 'Edit', edit_hotel_path(@hotel) %> |
<%= link_to 'Back', hotels_path %>